# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: "Doug Richardson: Game Development Notes"
email: doug@rekt.email
description: Doug Richardson's notes on game development, programming, Unreal Engine, Houdini, and other sometimes related topics.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dougrichardson.org" # the base hostname & protocol for your site
realname: Doug Richardson

# Build settings
markdown: kramdown

plugins:
  - jekyll-sitemap

collections:
    notes:
        output: true


