# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Projects
writings_title: Notes
writings_description: Notes on various topics.
email: doug@rekt.email
description: Doug Richardson makes video games at Reckless Cowboys. Here you'll find Doug's contact info and projects he's worked on.

baseurl: "" # the subpath of your site, e.g. /blog
url: "https://dougrichardson.org" # the base hostname & protocol for your site
realname: Doug Richardson
github_username:  drichardson
stackoverflow_userid: 196964
stackoverflow_username: doug-richardson
linkedin_username: douglasrichardson
twitter_username: dougrichardson_

# Build settings
markdown: kramdown
